baseURL = "https://sofoklis-karelis.netlify.app/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en"
paginate = 20
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
theme = "hugo-coder"
title = "Sofoklis Karelis"
[languages.en]
languageName = ":uk:"
[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1
[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2
[[languages.en.menu.main]]
name = "Projects"
url = "projects/"
weight = 3
[[languages.en.menu.main]]
name = "Contact me"
url = "contact/"
weight = 5
[languages.pt-br]
languageName = ":de:"
title = "Sofoklis Karelis"
[[languages.pt-br.menu.main]]
name = "Sobre"
url = "about/"
weight = 1
[[languages.pt-br.menu.main]]
name = "Blog"
url = "posts/"
weight = 2
[[languages.pt-br.menu.main]]
name = "Projetos"
url = "projects/"
weight = 3
[[languages.pt-br.menu.main]]
name = "Contato"
url = "contact/"
weight = 5
[languages.pt-br.params]
author = "Sofoklis Karelis"
description = "BSc-INFORMATIK"
info = "BSc-Informatik student"
keywords = "blogger,CyberSec trainee"
[params]
author = "SofoklisKarelis"
avatarURL = "images/avatar.jpg"
colorScheme = "auto"
commit = "https://github.com/sofokliskarelis"
customCSS = []
customJS = []
customSCSS = []
dateFormat = "January 30, 2022"
description = "I'm Sofoklis Karelis"
hideColorSchemeToggle = false
info = ["CyberSec on the rise", "BSc-Computer Science Student"]
keywords = "blogger,CyberSec"
maxSeeAlsoItems = 5
rtl = false
since = "2022"
[[params.social]]
icon = "fa fa-2x fa-github"
name = "Github"
url = "https://github.com/sofokliskarelis"
weight = 1
[[params.social]]
icon = "fa fa-2x fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/johndoe/"
weight = 4
[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
